name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

    - name: Build HTML
      uses: ammaraskar/sphinx-action@0.4
      run: |
        cd docs
        python -m pip install -r requirement.txt
        sphinx-build -D language='zh' -b html source build/zh
        sphinx-build -D language='en' -b html source build/en
    
    - name: Upload docs
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/